### ISSUE TITLE
NSCoder not implemented.

### ISSUE THREAD

**Issue by jcampbell05** [gautier-gdx/Hexacon#3]
It would be awesome if you could fix this crash.

**Comment by gautier-gdx** [comment]
Thanks for the feedback! I'll correct it this Saturday. 

If you're in a hurry don't hesitate to make a pull request

**Comment by gautier-gdx** [comment]
I think it's fixed, I never use storyboard so let me know

**Comment by jcampbell05** [comment]
I'll give it a go thankyou
